api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Added from FOSOAuthServerBundle tutorial
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_playground_oauth_server_auth_login:
    path:     /oauth/v2/auth_login
    defaults: { _controller: AppBundle:Security:login }

fos_playground_oauth_server_auth_login_check:
    path:     /oauth/v2/auth_login_check
    defaults: { _controller: AppBundle:Security:loginCheck }
# End Added from FOSOAuthServerBundle tutorial
