# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# Added from FOSOAuthServerBundle tutorial
parameters:
    platform.entity.user.class: AppBundle\Entity\User
    platform.user.provider.class: AppBundle\Provider\UserProvider

services:
    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine', getManagerForClass]
        arguments: ['%platform.entity.user.class%']

    platform.user.repository:
        class: AppBundle\Repository\UserRepository
        factory: ['@platform.user.manager', getRepository]
        arguments: ['%platform.entity.user.class%']

    platform.user.provider:
        class: '%platform.user.provider.class%'
        arguments: ['@platform.user.repository']
# End added from FOSOAuthServerBundle tutorial